/* ============================================================
   MAISON DORÉE — DATA
   Single source of truth for all restaurant content
   ============================================================ */

const RESTAURANT = {
  name:            'Maison Dorée',
  tagline:         'Where Every Meal Becomes a Memory',
  phone:           '+1 (234) 567-8900',
  whatsappNumber:  '1234567890',
  email:           'reservations@maisondoree.com',
  address: {
    street:  '123 Culinary Avenue',
    city:    'New York, NY 10001',
    country: 'United States',
  },
  hours: [
    { day: 'Monday',    time: 'Closed',            closed: true  },
    { day: 'Tuesday',   time: '12:00 – 10:00 PM',  closed: false },
    { day: 'Wednesday', time: '12:00 – 10:00 PM',  closed: false },
    { day: 'Thursday',  time: '12:00 – 10:00 PM',  closed: false },
    { day: 'Friday',    time: '12:00 – 11:00 PM',  closed: false },
    { day: 'Saturday',  time: '11:00 AM – 11:00 PM', closed: false },
    { day: 'Sunday',    time: '11:00 AM – 9:00 PM',  closed: false },
  ],
  timeSlots: [
    '12:00 PM', '12:30 PM', '1:00 PM',  '1:30 PM',  '2:00 PM',
    '6:00 PM',  '6:30 PM',  '7:00 PM',  '7:30 PM',  '8:00 PM',
    '8:30 PM',  '9:00 PM',  '9:30 PM',
  ],
  social: {
    instagram: '#',
    facebook:  '#',
    twitter:   '#',
  },
};

/* ---------- Menu Items ---------- */

const MENU_ITEMS = [
  /* ── STARTERS ─────────────────────────────────── */
  {
    id: 's1',
    category: 'starters',
    name: 'Seared Foie Gras',
    description: 'Pan-seared duck foie gras on brioche toast with Sauternes reduction, fig compote and microgreens.',
    price: 28,
    image: 'https://images.unsplash.com/photo-1639667870193-6fa5f47aa10c?auto=format&fit=crop&w=600&q=80',
    tags: ['Chef\'s Special'],
    isSpecial: true,
    isVegetarian: false,
  },
  {
    id: 's2',
    category: 'starters',
    name: 'Black Truffle Arancini',
    description: 'Crispy Arborio rice balls infused with black truffle, filled with aged fontina and served with truffle aioli.',
    price: 22,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
    tags: ['Vegetarian'],
    isSpecial: false,
    isVegetarian: true,
  },
  {
    id: 's3',
    category: 'starters',
    name: 'Oysters Rockefeller',
    description: 'Half-dozen East Coast oysters baked with spinach, Pernod cream, Gruyère and herb breadcrumbs.',
    price: 32,
    image: 'https://images.unsplash.com/photo-1606168094336-48f205a0a00c?auto=format&fit=crop&w=600&q=80',
    tags: ['Signature'],
    isSpecial: false,
    isVegetarian: false,
  },
  {
    id: 's4',
    category: 'starters',
    name: 'Burrata & Heirloom Tomato',
    description: 'Hand-pulled fresh burrata with heirloom tomatoes, aged balsamic, Sicilian olive oil and basil oil.',
    price: 18,
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=600&q=80',
    tags: ['Vegetarian', 'Gluten-Free'],
    isSpecial: false,
    isVegetarian: true,
  },

  /* ── MAINS ─────────────────────────────────────── */
  {
    id: 'm1',
    category: 'mains',
    name: 'Wagyu Beef Tenderloin',
    description: 'A5 Japanese Wagyu, 7oz, with truffle jus, pommes dauphine, grilled asparagus and bone marrow butter.',
    price: 89,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    tags: ['Chef\'s Special', 'Gluten-Free'],
    isSpecial: true,
    isVegetarian: false,
  },
  {
    id: 'm2',
    category: 'mains',
    name: 'Pan-Seared Sea Bass',
    description: 'Wild-caught Chilean sea bass with saffron beurre blanc, fennel purée, clams and samphire.',
    price: 65,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    tags: ['Gluten-Free'],
    isSpecial: false,
    isVegetarian: false,
  },
  {
    id: 'm3',
    category: 'mains',
    name: 'Duck Confit',
    description: 'Slow-cooked duck leg with cherry gastrique, Puy lentils, roasted root vegetables and duck jus.',
    price: 58,
    image: 'https://images.unsplash.com/photo-1544025162-d76538741f09?auto=format&fit=crop&w=600&q=80',
    tags: [],
    isSpecial: false,
    isVegetarian: false,
  },
  {
    id: 'm4',
    category: 'mains',
    name: 'Lobster Thermidor',
    description: 'Half Atlantic lobster flambéed with cognac, gratinéed with Gruyère cream and served with lobster bisque.',
    price: 95,
    image: 'https://images.unsplash.com/photo-1565474745528-d99e8bce6fcf?auto=format&fit=crop&w=600&q=80',
    tags: ['Signature'],
    isSpecial: false,
    isVegetarian: false,
  },
  {
    id: 'm5',
    category: 'mains',
    name: 'Rack of Lamb',
    description: 'French-trimmed rack of lamb with herb crust, Dauphinoise potatoes, haricots verts and rosemary jus.',
    price: 75,
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=600&q=80',
    tags: ['Gluten-Free'],
    isSpecial: false,
    isVegetarian: false,
  },
  {
    id: 'm6',
    category: 'mains',
    name: 'Wild Mushroom Risotto',
    description: 'Carnaroli risotto with porcini, chanterelle and shiitake mushrooms, Parmigiano Reggiano and truffle oil.',
    price: 48,
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=600&q=80',
    tags: ['Vegetarian'],
    isSpecial: false,
    isVegetarian: true,
  },

  /* ── DESSERTS ───────────────────────────────────── */
  {
    id: 'd1',
    category: 'desserts',
    name: 'Classic Crème Brûlée',
    description: 'Tahitian vanilla custard with a paper-thin caramelised crust, served with fresh raspberries.',
    price: 16,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80',
    tags: ['Gluten-Free'],
    isSpecial: false,
    isVegetarian: true,
  },
  {
    id: 'd2',
    category: 'desserts',
    name: 'Dark Chocolate Fondant',
    description: 'Warm 70% Valrhona chocolate fondant with a molten centre, Madagascan vanilla ice cream and praline.',
    price: 18,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80',
    tags: ['Chef\'s Special'],
    isSpecial: true,
    isVegetarian: true,
  },
  {
    id: 'd3',
    category: 'desserts',
    name: 'Tarte Tatin',
    description: 'Upside-down caramelised Granny Smith apple tart with flaky puff pastry and Calvados crème fraîche.',
    price: 14,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80',
    tags: ['Vegetarian'],
    isSpecial: false,
    isVegetarian: true,
  },
  {
    id: 'd4',
    category: 'desserts',
    name: 'Mille-Feuille',
    description: 'Layers of crisp puff pastry with vanilla diplomat cream, fresh strawberries and gold leaf.',
    price: 20,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80',
    tags: ['Signature'],
    isSpecial: false,
    isVegetarian: true,
  },

  /* ── DRINKS ─────────────────────────────────────── */
  {
    id: 'dr1',
    category: 'drinks',
    name: 'Château Margaux 2018',
    description: 'Premier Grand Cru Classé, Margaux. Notes of blackcurrant, cedar and violet with a silky long finish.',
    price: 180,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
    tags: ['Red Wine'],
    isSpecial: false,
    isVegetarian: true,
  },
  {
    id: 'dr2',
    category: 'drinks',
    name: 'Dom Pérignon 2013',
    description: 'Legendary Champagne with aromas of almond, white peach and citrus blossom. Extraordinary effervescence.',
    price: 220,
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=600&q=80',
    tags: ['Champagne', 'Signature'],
    isSpecial: true,
    isVegetarian: true,
  },
  {
    id: 'dr3',
    category: 'drinks',
    name: 'Classic Negroni',
    description: 'Hendrick\'s Gin, Campari and Cinzano Rosso stirred to perfection, served with an orange peel twist.',
    price: 22,
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=600&q=80',
    tags: ['Cocktail'],
    isSpecial: false,
    isVegetarian: true,
  },
  {
    id: 'dr4',
    category: 'drinks',
    name: 'Lavender Martini',
    description: 'Grey Goose vodka with house-made lavender syrup, lemon juice and butterfly pea flower tea.',
    price: 24,
    image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=600&q=80',
    tags: ['Cocktail', 'Signature'],
    isSpecial: false,
    isVegetarian: true,
  },
];

/* ---------- Gallery Images ---------- */

const GALLERY_IMAGES = [
  {
    id: 'g1',
    src: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80',
    alt: 'Elegant restaurant interior with warm amber lighting',
    tall: true,
  },
  {
    id: 'g2',
    src: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    alt: 'Beautiful food presentation on white plate',
    tall: false,
  },
  {
    id: 'g3',
    src: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    alt: 'Artfully plated fine dining dish',
    tall: false,
  },
  {
    id: 'g4',
    src: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80',
    alt: 'Chef preparing ingredients with precision',
    tall: false,
  },
  {
    id: 'g5',
    src: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80',
    alt: 'Exquisite wine and cheese pairing',
    tall: true,
  },
  {
    id: 'g6',
    src: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80',
    alt: 'Vibrant colourful salad with fresh ingredients',
    tall: false,
  },
  {
    id: 'g7',
    src: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=800&q=80',
    alt: 'Chef artfully plating a signature dish',
    tall: false,
  },
  {
    id: 'g8',
    src: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?auto=format&fit=crop&w=800&q=80',
    alt: 'Intimate candlelit table setting for two',
    tall: false,
  },
  {
    id: 'g9',
    src: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    alt: 'Grand restaurant dining room with crystal chandeliers',
    tall: true,
  },
];
